const { abrir, datalistSelecionar } = require('../../_scripts-comuns/cap_common.js');
(async () => {
  const { browser, page, ir, shot, chamar } = await abrir(__dirname);
  const lst = await chamar('POST', 'contarecorrente/listar', {});
  for (const c of (lst.data || [])) if ((c.descricao || '') === 'ALUGUEL DA SALA 2') await chamar('DELETE', `contarecorrente/${c.idContaRecorrente}`);
  await ir('/cadastro/contasrecorrentes');
  await shot('00-lista-inicial');
  await page.click('button:has-text("Novo")'); await page.waitForSelector('.modal.show'); await page.waitForTimeout(800);
  const m = page.locator('.modal.show').last();
  const ins = m.locator('input[placeholder="Digite e selecione"]');
  await datalistSelecionar(page, ins.nth(0), '', (x) => !x.includes('*') && !/teste/i.test(x));
  await datalistSelecionar(page, ins.nth(1), 'Aluguel');
  await datalistSelecionar(page, ins.nth(2), 'Administrativo');
  await m.locator('input[type=text]').nth(3).fill('ALUGUEL DA SALA 2');
  const valor = m.locator('input[type=text]').nth(4); await valor.click(); await valor.fill('1500,00');
  await m.locator('input[type=number]').first().fill('10');
  const hoje = new Date(); const dd = String(hoje.getDate()).padStart(2, '0') + '/' + String(hoje.getMonth() + 1).padStart(2, '0') + '/' + hoje.getFullYear();
  await m.locator('input[bsdatepicker]').first().fill(dd); await page.keyboard.press('Escape'); await page.waitForTimeout(300);
  await m.locator('input[type=number]').nth(1).fill('30');
  await shot('01-novo-modal-preenchido');
  await m.locator('button:has-text("Salvar")').click(); await page.waitForTimeout(1800);
  await page.waitForSelector('.modal.show', { state: 'detached' }).catch(() => {});
  await shot('02-apos-salvar');
  await page.click('button:has-text("Log do Job")'); await page.waitForSelector('.modal.show'); await page.waitForTimeout(1200);
  await shot('03-log-job');
  await page.click('button:has-text("Forçar Execução Agora")'); await page.waitForTimeout(3500);
  await shot('04-log-job-executado');
  await ir('/financeiro/contapagar');
  await shot('05-conta-pagar-gerada');
  await browser.close(); console.log('OK');
})().catch(e => { console.error('FALHA:', e.message.slice(0, 500)); process.exit(1); });
