const { abrir, datalistSelecionar } = require('../../_scripts-comuns/cap_common.js');
(async () => {
  const { browser, page, ir, shot, chamar } = await abrir(__dirname);
  const lst = await chamar('POST', 'contapagar/listar', {});
  
  await ir('/financeiro/contapagar');
  await shot('00-lista-inicial');
  console.log('botoes:', (await page.locator('.content-wrapper button:visible, .content-wrapper a:visible').allInnerTexts()).map(x => x.trim()).filter(Boolean).slice(0, 12).join('|'));
  await page.locator('button:has-text("Filtro rápido")').click(); await page.waitForSelector('.modal.show'); await page.waitForTimeout(700);
  await shot('00b-filtro-rapido');
  await page.locator('.modal.show button:has-text("Fechar")').first().click(); await page.waitForTimeout(700);
  await page.click('button:has-text("Novo")'); await page.waitForSelector('.modal.show'); await page.waitForTimeout(800);
  const m = page.locator('.modal.show').last();
  const ins = m.locator('input[placeholder="Digite e selecione"]');
  await datalistSelecionar(page, ins.nth(0), '', (x) => !x.includes('*') && !/teste/i.test(x));
  await datalistSelecionar(page, ins.nth(1), 'Material de Consumo');
  await datalistSelecionar(page, ins.nth(2), 'Administrativo');
  const tx = m.locator('input[type=text]');
  console.log(await tx.evaluateAll(a => a.map(e => e.placeholder + '|' + (e.getAttribute('mask') || ''))));
  await m.locator('input[type=text]').nth(3).fill('COMPRA DE MATERIAL DE ESCRITORIO');
  const valor = m.locator('input[type=text]').nth(4); await valor.click(); await valor.fill('350,00');
  await m.locator('select').selectOption({ label: '1 - Boleto' });
  const hoje = new Date(); const dd = String(hoje.getDate()).padStart(2, '0') + '/' + String(hoje.getMonth() + 1).padStart(2, '0') + '/' + hoje.getFullYear();
  await m.locator('input[placeholder="MM/AAAA"]').fill(dd.slice(3));
  await m.locator('input[bsdatepicker]').last().fill(dd); await page.keyboard.press('Escape'); await page.waitForTimeout(300);
  await shot('01-novo-modal-preenchido');
  await m.locator('button:has-text("Salvar")').click(); await page.waitForTimeout(1800);
  await page.waitForSelector('.modal.show', { state: 'detached' }).catch(() => {});
  await shot('02-apos-salvar');
  await page.locator('tr').filter({ hasText: 'COMPRA DE MATERIAL' }).filter({ hasText: '1 - Aberto' }).last().locator('button[title="Pagamento / Acerto"]').click();
  await page.waitForSelector('.modal.show'); await page.waitForTimeout(1200);
  const p = page.locator('.modal.show').last();
  const vp = p.locator('input[type=text]').nth(1); await vp.click(); await vp.fill('350,00'); await vp.press('Tab');
  await p.locator('select').nth(0).selectOption({ label: 'Cartão de Crédito' });
  await p.locator('select').nth(1).selectOption({ label: 'BANCO BRASIL' });
  await page.waitForTimeout(600);
  await shot('03-pagamento-preenchido');
  await p.locator('button:has-text("Lançar")').click(); await page.waitForTimeout(1800);
  await shot('04-apos-lancar-pagamento');
  await browser.close(); console.log('OK');
})().catch(e => { console.error('FALHA:', e.message.slice(0, 500)); process.exit(1); });
